### ISSUE TITLE
新增发言排行 Web 端查询

### ISSUE THREAD

**Issue by JoinChang** [JoinChang/LxBot-QQ#12]
利用 websocket 与服务器交互信息。

https://bot.lxns.org/rank/<Token\>

**\<Token\>** 为在群中输入 `/rank web <1d|1w>` 返回的一个值，将会自动与链接拼接发送，用户可以通过该链接查询更详细的本群发言排行。链接生成后的排行会自动缓存（即单次生成内不会实时更新），单群仅能同时生成一次链接，同时该链接会在一段时间后过期。

您可以通过该链接查询到以下信息：
- QQ 号
- QQ 名（群名片看情况）
- QQ 头像
- 所选范围的发言条数
- 查询对象：**群内所有在所选范围中发言过的人**
- 总发言条数
- 总发言人数

*注意：该指令并不支持查询发言字数*

**Comment by XxLittleCxX** [comment]
神

**Comment by wyapx** [comment]
LxnsNB
