### ISSUE TITLE
缺少这些歌的简写形式

### ISSUE THREAD

**Issue by xxuurruuii** [JoinChang/LxBot-QQ#30]
harotopia
esm
lunarorbit
your voice so
your voice so...
dot to dot
call my name

**Comment by JoinChang** [comment]
已经添加：
- `esm`：Engine x Start!!(melody remix)
- `lunarorbit`：LunarOrbit -believe in the Espebranch road-

已经存在：
- `your voice so` 使用 `yourvoiceso` 代替。
- `dot to dot` 使用 `dottodot` 代替。
- `call my name` 使用 `callmyname` 代替。
